plugins {
    id 'com.github.johnrengelman.shadow'
}

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

loom {
    forge {
        mixinConfig "inspectability.mixins.json"
    }
}

repositories {
    maven {
        name = "Forge"
        url = "https://maven.minecraftforge.net/"
    }

    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }

    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
    mavenCentral()
}


dependencies {
    forge "net.minecraftforge:forge:$rootProject.minecraft_version-$rootProject.forge_version"

    // forgeRuntimeLibrary "com.google.code.findbugs:jsr305:3.0.2"
    // shadowBundle "com.google.code.findbugs:jsr305:3.0.2"

    modImplementation "dev.architectury:architectury-forge:$rootProject.architectury_api_version"

    common(project(path: ':common', configuration: 'namedElements'))

    shadowBundle(project(path: ':common', configuration: 'transformProductionForge'))

    modCompileOnly "mezz.jei:jei-1.20.1-forge-api:$rootProject.jei_version"
    modRuntimeOnly "mezz.jei:jei-1.20.1-forge:$rootProject.jei_version"

    modRuntimeOnly "curse.maven:configured-457570:5180900"
}

processResources {
    def expandProps = [
        "version": project.version,
        "mod_id": rootProject.mod_id,
        "mod_name": rootProject.mod_name,
        "mod_license": rootProject.mod_license,
        "mod_authors": rootProject.mod_authors,
        "mod_description": rootProject.mod_description,
        "issue_tracker_url": rootProject.issue_tracker_url,
        "minecraft_version_range": rootProject.minecraft_version_range,
        "architectury_version_range": rootProject.architectury_version_range,
        "forge_version_range": rootProject.forge_version_range,
        "loader_version_range": rootProject.loader_version_range
    ]

    inputs.properties expandProps

    filesMatching('META-INF/mods.toml') {
        expand expandProps
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

remapJar {
    input.set shadowJar.archiveFile
    destinationDirectory.set(rootProject.file("builds/forge"))
}